### ISSUE TITLE
Hide options after finishing processing

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/toucan#105]
With #104 we have many options as parameters in each function, it would be convenient to hide them after successfully finishing the process and obtain the results in each function.

If there was an error the user can load the correct files and interact with the options.

**Comment by aguilerapy** [comment]
Related #95

**Comment by romifz** [comment]
Besides the options, we need to disable the file upload box and URL inputs after a process has finished correctly.

Or, we can consider if we want to give the user the option to continue using the same feature, either by a Clear/Start Again button or allowing them to continue loading files.
