### ISSUE TITLE
mapping-sheet: Add support for flattening extended schemas

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/toucan#12]
Make the "generate a spreadsheet version of OCDS schema" function accept extended schemas.

With this feature we could:

* Link to a flattened version of the extended schema from each extension's documentation page in the [extension explorer](https://extensions.open-contracting.org/en/extensions/additionalContactPoint/master/)
* Link to a flattened version of the OCDS for PPPs schema from the [OCDS for PPPs documentation](http://standard.open-contracting.org/profiles/ppp/latest/en/reference/)

If this was implemented by a url parameter (e.g. schema_url) we could pass any schema to the tool, including the OC4IDS schema.

In the case of extensions we'd need to consider whether OCDSKit web should do the patching of the schema itself, or whether it should accept a schema patched outside of the tool (perhaps generating the patched schema could be added to the extension explorer build process).

Separately we should also consider including a link to the flattened OCDS schema in the core documentation.

**Comment by romifz** [comment]
Done

**Comment by jpmckinney** [comment]
Reopening just for me to create the follow-up issues Duncan mentions in Extension Explorer, etc.
