### ISSUE TITLE
Allow the results of one function to be the input for another function

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/toucan#14]
So that users don't need to download and upload files between functions, to support using the tool with larger files and/or with poor connectivity.

e.g. after combining releases into a release package a user could then submit the release package to be compiled into a record package.

**Comment by aguilerapy** [comment]
Here's an example of how we could solve it.

![Screenshot_2020-02-07 OCDS Toucan](https://user-images.githubusercontent.com/48607824/73998610-f1b30f80-4940-11ea-9848-eda04c7898fc.png)

What do you think about this? If we select the function in "Send to function" and click on "Go!", redirects us to the selected function page and adds the file.

![Captura de pantalla de 2020-02-07 00-27-25](https://user-images.githubusercontent.com/48607824/73998677-2921bc00-4941-11ea-9f3d-af582b95da08.png)

**Comment by jpmckinney** [comment]
@romifz @yolile @pindec @mrshll1001 What do you think? We can also discuss at the retreat.

**Comment by aguilerapy** [comment]
Any update on this issue?

**Comment by yolile** [comment]
I think that we can go with the @aguilerapy suggestion: after a step ends show the next possible ones. Or, before start the first step, select all the steps you want to follow.

**Comment by jpmckinney** [comment]
I like the "Send to function" approach 👍

**Comment by duncandewhurst** [comment]
Looks good to me! Maybe it should read "Send results to function" to be totally clear

**Comment by aguilerapy** [comment]
closed by #96
