### ISSUE TITLE
Add support for combine-releases-packages and combine-record-packages

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/toucan#20]
Also, if a file is a JSON array of packages, append each package to the list of packages to process, instead of appending the JSON array.

Since some OCDS data is published as a JSON array of packages, this avoids a user having to split the array into individual files before using combine-*-packages.

**Comment by duncandewhurst** [comment]
+1 to adding support for combine-release-packages as a priority

**Comment by jpmckinney** [comment]
Note: The (unreleased) 0.1.0 version of OCDS Kit now has library functions for these.

**Comment by jpmckinney** [comment]
This version of OCDS Kit has now been released.

**Comment by jpmckinney** [comment]
Closed by #52
