### ISSUE TITLE
Transfer server to OCP's Bytemark

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/toucan#28]
`ocdskit-web.default.opendataservices.uk0.bigv.io`

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move remaining servers to OCP's Bytemark account](https://trello.com/c/becHQKUG/15-move-remaining-servers-to-ocps-bytemark-account)

**Comment by odscjames** [comment]
This has now been done.
