### ISSUE TITLE
Rename repository and URL?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/toucan#29]
Since it includes an interface to Flatten Tool, it might be confusing to call it "OCDS Kit Web". A generic name could be "OCDS Multi-Tool". In terms of product identity, this is a collection of tools for pre-processing / transforming / re-shaping / preparing data for analysis. Is there a name that could fit that identity? If it were "OCDS Pre-Processor" or "OCDS Transformer" do you think enough people would know what it means?

Thoughts? @romifz @yolile @robredpath @duncandewhurst 

I had drafted some [product naming guidelines](https://docs.google.com/document/d/1qnfx9PWqizuJsTVsSGyWBTxDHd-lifhtnkyLi7Nayig/edit) when we were naming Kingfisher.

If we rename, we'll also have to add a new CNAME.

**Comment by romifz** [comment]
"OCDS Multi-Tool" sounds best for me. It communicates the idea of several tools doing different operations. "OCDS Transformer" is a good one too.

**Comment by yolile** [comment]
Or maybe just "OCDS Tools" ?

**Comment by jpmckinney** [comment]
"OCDS Tools" is maybe too generic, and starts to get confusing with the OCDS Tools Directory: https://www.open-contracting.org/resources/open-contracting-tools-directory/

**Comment by robredpath** [comment]
I like "OCDS Multi-tool". I think it does, but we should check that the concept exists across all the places that we're expecting OCDS to be applicable to in the near future.

**Comment by duncandewhurst** [comment]
OCDS Multi-tool sounds good to me.

Other options could be OCDS Toolbox or OCDS Toolkit, but they are probably too similar to the Tools Directory and OCDSkit respectively.

**Comment by LindseyAM** [comment]
Suggest OCDS Pelican to keep with the Kingfisher trend.  Sound good? Or better suggestions?

**Comment by GavinHayman** [comment]
Multi-tool is clear. On the aviary theme, toucans have large, useful beaks that serve a number of purposes. OCDS Toucan is as appealing image.

**Comment by jpmckinney** [comment]
I'm happy with a non-descriptive, thematic name like OCDS Pelican or OCDS Toucan. "Multi-tool" isn't much more descriptive; users will still need a description of what it offers – it just clarifies that it does more than one thing.

**Comment by LindseyAM** [comment]
Alright. Let's go with Toucan on this one and Pelican can be our next tool.

**Comment by jpmckinney** [comment]
I opened two pull requests #32 and #33 and added an A record for toucan.open-contracting.org. 

@romifz Do we know if anyone is already using ocdskit.open-contracting.org? If not, then I can delete its DNS entry.

**Comment by romifz** [comment]
I think @yolile showed it in a recent training in Colombia. If she shared the link during the training, could we add a temporal redirect?

**Comment by jpmckinney** [comment]
Sure, I think that requires a change to OpenDataServices/opendataservices-deploy cc @odscjames

**Comment by jpmckinney** [comment]
I created issues and added a Trello card for the deployment issues.

Note: I made a DNS error, so ocdskit.open-contracting.org will be back in less than an hour if you happened to retrieve the bad entry.

**Comment by odscjames** [comment]
http://ocdskit.open-contracting.org/ redirects to http://toucan.open-contracting.org/ - done
