### ISSUE TITLE
Update description of tool and link from OCP website 

### ISSUE THREAD

**Issue by LindseyAM** [open-contracting/toucan#30]
Once we decide what to name tool in #29 please also add some text to http://ocdskit.open-contracting.org/ explaining what the tool is and linking to the forthcoming learning lab on how to use it.  

please also add to the USE section of the 7 steps and the Resources page of OCP website

**Comment by jpmckinney** [comment]
* Added to Use step of 7 steps: https://www.open-contracting.org/implement/#/5
* Added to OCP Resources: https://www.open-contracting.org/resources/ocds-toucan/

The Learning Lab is not available yet – we can create an issue to integrate it when ready.

I created #30 for adding more descriptive text to the homepage.
