### ISSUE TITLE
Different input/output options

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/toucan#42]
Based on demand, we can consider adding URL input (instead of upload only), and the option to output to Google Drive. Proposed by @robredpath at OCDS Retreat.

**Comment by aguilerapy** [comment]
For #67 to work it's necessary to create credentials for the Google Drive API with an OCP account. Here we have a [guide](https://developers.google.com/adwords/api/docs/guides/authentication#generate_oauth2_credentials).

Then just configure the environment variable: `OCDS_TOUCAN_CREDENTIALS_DRIVE` in `settings.py` to point to a JSON file that contains the credentials.

**Comment by jpmckinney** [comment]
The guide is for Adwords, so our use is a little different.

My main steps were:

1. Create new project
1. Enable Google Drive API
1. Setup consent screen with the drive.file scope
1. Create credentials
1. Submit for verification

Now waiting on verification.

**Comment by aguilerapy** [comment]
Both options are merged and deployed ([URL](https://github.com/open-contracting/toucan/pull/87) and [Google Drive](https://github.com/open-contracting/toucan/pull/67)).
