### ISSUE TITLE
Error reporting and warning messages

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/toucan#43]
From a project card:

* Error display behaviour on client page
* Add javascript alert before leaving action page

**Comment by jpmckinney** [comment]
See the TODO in the code about handing invalid date errors.

We can add tests for invalid JSON, non-OCDS JSON, etc. and improve their error handling.

**Comment by jpmckinney** [comment]
@romifz Is there anything more to do for this issue? I'm not sure what "Add javascript alert before leaving action page" is about.

**Comment by romifz** [comment]
Sorry, what I meant is that there should be some alert or message to prevent the user from navigating away when uploading files. This is done, so I think we can close this issue for now.
