### ISSUE TITLE
Use GZipMiddleware instead of using zipfile

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/toucan#44]
@romifz Is there a reason package-releases creates a ZIP file? If it's just to make the download size smaller, we can use GZipMiddleware.

**Comment by romifz** [comment]
Sounds good, we can do that.

**Comment by romifz** [comment]
Although in the other hand, plain json/csv files can get quite large and there is no good reason to save them that way...

**Comment by jpmckinney** [comment]
True, plus we need to ZIP the output if there are multiple files in the output. I figure it's better to be consistent, and some recent OSes automatically UNZIP files anyway. So, I'll close this.
