### ISSUE TITLE
Add more descriptive text to homepage

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/toucan#47]
Follow-up from #30

**Comment by romifz** [comment]
Would a simple block of text be enough?

> OCDS Toucan supports the use of [OCDS](https://standard.open-contracting.org) data with a set of online tools for common file transformations, such as
> * Combine release or record packages
> * Generate compiled releases
> * Transform a release package to Excel or CSV files
> * and more.
>
> You can upload up to 20 files for each operation, and files should not be bigger than 20mb. Please check each tool as some can have additional requirements for your files. Results are downloadable for up to 2 days after.
>
> Please report any issues to data[at]open-contracting.org or add an issue in our [GitHub repository](https://github.com/open-contracting/toucan/issues/).

Is there something else we should add to the homepage?

**Comment by jpmckinney** [comment]
Good start, my edit:

You sometimes need to transform [OCDS](https://standard.open-contracting.org/) data before you can use it or publish it. OCDS Toucan offers a set of transformation tools to:

* Create a [release package](https://standard.open-contracting.org/latest/en/schema/release_package/) from individual [releases](https://standard.open-contracting.org/latest/en/getting_started/releases_and_records/#releases)
* Combine many small packages into a large package
* Transform release packages into a [record package](https://standard.open-contracting.org/latest/en/schema/record_package/) with compiled releases and versioned releases
* Upgrade from an old version of OCDS to a new version
* Convert release packages to/from Excel and CSV
* Generate a spreadsheet version of OCDS schema

You can upload up to 20 files to each tool, and each file should be less than 20MB. Results remain available for 2 days.

If you have more or larger files, try using [OCDS Kit](https://ocdskit.readthedocs.io/en/latest/) from the command line. Please report any issues to data@open-contracting.org or create an issue on [GitHub](https://github.com/open-contracting/toucan/issues).

**Comment by aguilerapy** [comment]
![Screenshot_2020-02-18 OCDS Web Tools - Home](https://user-images.githubusercontent.com/48607824/74738965-ac42ec00-5236-11ea-82b6-815bf71123ac.png)

We can add one button newt to language menu and when clicking show a popup or a block of text in toucan main page or just redirect to another page. What do you think? @jpmckinney @romifz

**Comment by aguilerapy** [comment]
![Screenshot_2020-02-18 OCDS Web Tools - Home(1)](https://user-images.githubusercontent.com/48607824/74743290-e2846980-523e-11ea-936e-ab8ec54c0eb9.png)

For example, this could be the redirect page.

**Comment by jpmckinney** [comment]
I think we can put that content block on the homepage, beneath the blocks that link to the tools.

**Comment by aguilerapy** [comment]
![Screenshot_2020-02-24 OCDS Web Tools - Home](https://user-images.githubusercontent.com/48607824/75157869-c297ee80-56f3-11ea-8ed2-2614635a1ea8.png)

Like this? @jpmckinney

**Comment by jpmckinney** [comment]
Yes!

**Comment by aguilerapy** [comment]
Closed by #79
