### ISSUE TITLE
mapping-sheet: Add link to definitions of columns

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/toucan#63]
e.g. "You can [refer to the definitions of the spreadsheet's columns](https://ocdskit.readthedocs.io/en/latest/api/mapping_sheet.html)."

**Comment by aborruso** [comment]
But please in this page https://toucan.open-contracting.org/mapping-sheet/ :)

Thank you

**Comment by jpmckinney** [comment]
Closed by #73

**Comment by aborruso** [comment]
Thank you very much @jpmckinney

**Comment by jpmckinney** [comment]
Our pleasure - thank you for reporting the issue to us :)
