### ISSUE TITLE
Error in Convert to JSON

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/toucan#64]
In `uploadfile` function we have `file_type = request.POST.get('type', None)` setting none in file_type for `to-json.html`, apparently it doesn't get the value "type": "xlsx zip", then, in `invalid_request_file_message`, this is false:
` if file_type == 'xlsx zip': return` , does't run the return and fail the sentence: `data = json.load(f)` for xlsx or zip files.

**Comment by jpmckinney** [comment]
Closed by #65
