### ISSUE TITLE
Add 'source' parameter usage instructions for mapping-sheet

### ISSUE THREAD

**Issue by romifz** [open-contracting/toucan#70]
The `source` parameter can be used to produce a mapping sheet from a schema's URL. We need to document this somewhere in the site.

**Comment by romifz** [comment]
Same with the `extension` parameter, which can be used to produce a patched schema. 

See #49.

**Comment by jpmckinney** [comment]
Is this the same issue as #68?

**Comment by romifz** [comment]
Yes it is, sorry! Closing this one.
