### ISSUE TITLE
Flatten Tool: Expose --preserve-fields

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/toucan#85]
https://flatten-tool.readthedocs.io/en/latest/flatten/#preserve-fields

The most basic implementation would be upload JSON file(s), and then check/uncheck which fields to include in the flattened files.

A better, advanced version would be to allow the user to check boxes for use cases. On the backend, we will have already organized the fields into use cases.

**Comment by romifz** [comment]
@juanpane suggested to add a way to search for fields. Personally I think something like a [tree selector](https://mbraak.github.io/jqTree/examples/08_multiple_select/) may be useful.

**Comment by jpmckinney** [comment]
We can also consider https://select2.org It doesn't have multiple levels of hierarchy (though, if we put the full path, the hierarchy will be evident), but it does have a lot of nice features.

**Comment by jpmckinney** [comment]
Closed by #108
