### ISSUE TITLE
Error message hides "start" button

### ISSUE THREAD

**Issue by yolile** [open-contracting/toucan#94]
In some screen resolutions when you get an error message the "start" button is not visible anymore.

![image](https://user-images.githubusercontent.com/6834122/82222156-e5026800-98ee-11ea-8166-e458ce66146f.png)

I think that we can a) add a scroll if the content of the page doesn't fit in the page and/or b) make the "Open Contracting Partnership" footer smaller c) ensure that the site is responsive

**Comment by aguilerapy** [comment]
Fixed in https://github.com/open-contracting/toucan/pull/96/commits/cf6e4c85eec53f2315e65c0c695d92af7a32d337. Waiting merge.
